# A Short Guide to Using `.loc` and `.iloc` in Pandas

Pandas' `.loc` is a powerful label-based indexing tool that allows for precise data selection and manipulation within DataFrames. Understanding when and how to use `.loc` can enhance your data handling efficiency and accuracy.

## When to Use `.loc`

- **Label-Based Selection:** Use `.loc` when you need to select rows and columns based on their labels (index names and column names) rather than their integer positions.
- **Conditional Filtering:** It is ideal for selecting subsets of data that meet specific conditions.
- **Reassigning Data:** `.loc` is essential when you need to modify data within the DataFrame based on labels or conditions.

In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000]
}
df = pd.DataFrame(data, index=['A', 'B', 'C', 'D'])
df

      Name  Age  Salary
A    Alice   25   50000
B      Bob   30   60000
C  Charlie   35   70000
D    David   40   80000

## Differences Between `.loc` Slicing and Simple Slicing

**1. Label vs. Position-Based:**
- **`.loc` Slicing:** Uses label-based indexing. Both the start and end labels are inclusive.

In [2]:
df.loc['A':'C']  # Includes rows labeled 'A', 'B', and 'C'

      Name  Age  Salary
A    Alice   25   50000
B      Bob   30   60000
C  Charlie   35   70000

- **Simple Slicing (`[]`):** With integers, it slices rows by position and the end index is exclusive. With labels, `df['A':'C']` also works and *includes* the end label. Because the two behave differently, it is clearer to use `.iloc` for positions and `.loc` for labels.

```python
df[0:3]  # Includes the first three rows (positions 0, 1, 2)
```

**2. Accessing Columns:**
- **With `.loc`:** You can specify both row and column labels.

In [3]:
df.loc['A':'C', 'Age':'Salary']

   Age  Salary
A   25   50000
B   30   60000
C   35   70000

- **With Simple Slicing:** Limited to row selection unless combined with other methods.
```python
df[['Name', 'Age']]
```

**3. Handling Non-Unique or Missing Labels:**
- **`.loc`:** Raises a `KeyError` if labels are not found, ensuring you catch indexing errors.
- **Simple Slicing:** More flexible but can lead to unintended selections if labels overlap or are missing.

## Reassigning Values with `.loc`

`.loc` provides a reliable way to modify DataFrame values based on labels or conditions without affecting unintended parts of the data.

**Example: Updating Specific Rows and Columns**

In [4]:
# Reassign the Salary for Bob to 65000
df.loc['B', 'Salary'] = 65000
df

      Name  Age  Salary
A    Alice   25   50000
B      Bob   30   65000
C  Charlie   35   70000
D    David   40   80000



**Example: Conditional Reassignment**

In [5]:
df.loc[df['Salary'] < 70000, 'Age'] += 1
df

      Name  Age  Salary
A    Alice   26   50000
B      Bob   31   65000
C  Charlie   35   70000
D    David   40   80000

### Benefits of Using `.loc` for Reassignment:
- **Precision:** Targets specific rows and columns without ambiguity.
- **Safety:** Prevents accidental modification of unintended data segments.
- **Clarity:** Makes the code more readable and intentions explicit.

## Summary

- **Use `.loc`** for label-based row and column selection, especially when dealing with non-integer indices.
- **Differentiate from simple slicing** by recognizing `.loc` includes the end label and allows simultaneous row and column access.
- **Leverage `.loc` for reassignment** to modify DataFrame values safely and precisely based on labels or conditions.

By incorporating `.loc` into your Pandas workflow, you can achieve more controlled and readable data manipulation, leading to cleaner and more maintainable code.

### `.loc` exercises

- Select rows 'A' to 'C' and columns 'Name' and 'Salary'.
- Set 'Age' at index 'D' to 41.

In [6]:
# Your code here

## Using `.iloc`

- **What**: Integer position-based selection.
- **Rows, cols**: `df.iloc[row_positions, col_positions]`.
- **Slices**: End index is exclusive, like standard Python slicing.

Examples:

In [7]:
# First two rows, first two columns
df.iloc[0:2, 0:2]

    Name  Age
A  Alice   26
B    Bob   31

In [8]:
# Third row, 'Salary' column by position
df.iloc[2, 2]

np.int64(70000)

In [9]:
# Non-contiguous rows and columns
df.iloc[[0, 3], [1, 2]]

   Age  Salary
A   26   50000
D   40   80000

### `.iloc` exercises

- Get the last two rows and the 'Age' and 'Salary' columns using positions.
- Select the first and last rows, and the second column only.

In [10]:
# Your code here